--1 nombre de client par region pays ville (decroissant)
Select COUNT(DISTINCT RBONDAZ.CUSTOMER.CUSTOMER_ID) , upper(RBONDAZ.CITY.CITY_NAME), trim(upper(RBONDAZ.REGION.REGION_NAME)), upper(RBONDAZ.COUNTRY.COUNTRY_NAME), EXTRACT(year from RBONDAZ.SALES.INVOICE_DATE)
from RBONDAZ.CUSTOMER
join RBONDAZ.SALES on RBONDAZ.CUSTOMER.CUSTOMER_ID = RBONDAZ.SALES.CUSTOMER_ID
join RBONDAZ.CITY on rbondaz.CUSTOMER.CITY_ID = rbondaz.CITY.CITY_ID
join RBONDAZ.REGION on RBONDAZ.REGION.REGION_ID = rbondaz.CITY.REGION_ID
join RBONDAZ.COUNTRY on RBONDAZ.REGION.COUNTRY_ID = RBONDAZ.COUNTRY.COUNTRY_ID
GROUP BY RBONDAZ.CITY.CITY_NAME, RBONDAZ.REGION.REGION_NAME, RBONDAZ.COUNTRY.COUNTRY_NAME, EXTRACT(year from RBONDAZ.SALES.INVOICE_DATE)
order by 5 desc;

--2 nb clients potentiels par region pays ville (decroissant)
Select COUNT(DISTINCT RBONDAZ.CUSTOMER.CUSTOMER_ID) as nb_customers , upper(RBONDAZ.CITY.CITY_NAME), trim(upper(RBONDAZ.REGION.REGION_NAME)), upper(RBONDAZ.COUNTRY.COUNTRY_NAME), EXTRACT(year from RBONDAZ.RESERVATION.RESERVATION_DATE) as year
from RBONDAZ.CUSTOMER
join RBONDAZ.RESERVATION on RBONDAZ.CUSTOMER.CUSTOMER_ID = RBONDAZ.RESERVATION.CUSTOMER_ID
join RBONDAZ.CITY on rbondaz.CUSTOMER.CITY_ID = rbondaz.CITY.CITY_ID
join RBONDAZ.REGION on RBONDAZ.REGION.REGION_ID = rbondaz.CITY.REGION_ID
join RBONDAZ.COUNTRY on RBONDAZ.REGION.COUNTRY_ID = RBONDAZ.COUNTRY.COUNTRY_ID
GROUP BY RBONDAZ.CITY.CITY_NAME, RBONDAZ.REGION.REGION_NAME, RBONDAZ.COUNTRY.COUNTRY_NAME, EXTRACT(year from RBONDAZ.RESERVATION.RESERVATION_DATE)
order by 5 desc;



--3 nombre de clients par tranche d'age
SELECT COUNT(DISTINCT RBONDAZ.CUSTOMER.CUSTOMER_ID) as count,
CASE
    WHEN EXTRACT(year from current_date) - EXTRACT(year from RBONDAZ.CUSTOMER.BIRTH_DATE) BETWEEN 0 and 29 then 'jeunes'
    WHEN EXTRACT(year from current_date) - EXTRACT(year from RBONDAZ.CUSTOMER.BIRTH_DATE) BETWEEN 30 and 60 then 'pré-vieux'
    ELSE 'vieux'
END as age
from RBONDAZ.CUSTOMER
group by
CASE
    WHEN EXTRACT(year from current_date) - EXTRACT(year from RBONDAZ.CUSTOMER.BIRTH_DATE) BETWEEN 0 and 29 then 'jeunes'
    WHEN EXTRACT(year from current_date) - EXTRACT(year from RBONDAZ.CUSTOMER.BIRTH_DATE) BETWEEN 30 and 60 then 'pré-vieux'
    ELSE 'vieux'
END;


--4 nb client dans chaque resort
select SUM(RBONDAZ.INVOICE_LINE.INVOICE_NB_GUESTS) as nb_clients,SERVICE_NAME, RBONDAZ.RESORT.RESORT_NAME
from RBONDAZ.INVOICE_LINE
join RBONDAZ.SERVICE on INVOICE_LINE.SERVICE_ID = SERVICE.SERVICE_ID
join RBONDAZ.SERVICE_LINE on SERVICE.SERVICE_LINE_ID = SERVICE_LINE.SERVICE_LINE_ID
join RBONDAZ.RESORT on SERVICE_LINE.RESORT_ID = RESORT.RESORT_ID
group by RESORT_NAME, SERVICE.SERVICE_NAME;

--5 NB futur clients dans chaque resort
select SUM(RBONDAZ.RESERVATION_LINE.FUTUR_GUESTS) as nb_clients,SERVICE_NAME, RBONDAZ.RESORT.RESORT_NAME
from RBONDAZ.RESERVATION_LINE
join RBONDAZ.SERVICE on RESERVATION_LINE.SERVICE_ID = SERVICE.SERVICE_ID
join RBONDAZ.SERVICE_LINE on SERVICE.SERVICE_LINE_ID = SERVICE_LINE.SERVICE_LINE_ID
join RBONDAZ.RESORT on SERVICE_LINE.RESORT_ID = RESORT.RESORT_ID
group by RESORT_NAME, SERVICE_NAME;

--6 liste des parrains de nos clients et filleuls
select c.CUSTOMER_ID,
       TRIM(c.FIRST_NAME) as first_name_filleul,
       TRIM(c.LAST_NAME) as last_name_filleul,
       c.SPONSOR_ID,
       TRIM(cu.FIRST_NAME) as first_name_parrain,
       TRIM(cu.LAST_NAME) as last_name_parrain
from RBONDAZ.CUSTOMER c
left outer join RBONDAZ.CUSTOMER cu on  c.SPONSOR_ID = cu.CUSTOMER_ID;

--7 CA annuel global
SELECT EXTRACT(year from s.invoice_date) year, SUM(se.PRICE*il.INVOICE_NB_GUESTS*il.INVOICE_DAYS) CA_annuel from RBONDAZ.SALES s
join RBONDAZ.INVOICE_LINE il on s.INVOICE_LINE_ID = il.INVOICE_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
group by EXTRACT(year from s.invoice_date)
order by EXTRACT(year from s.invoice_date);

--7 bis CA_ annuel previsionnel
SELECT EXTRACT(year from re.RESERVATION_DATE) year, SUM(se.PRICE*il.RESERVATION_DAYS*il.FUTUR_GUESTS) CA_annuel from RBONDAZ.RESERVATION re
join RBONDAZ.RESERVATION_LINE il on re.RESERVATION_ID= il.RESERVATION_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
group by EXTRACT(year from re.RESERVATION_DATE)
order by EXTRACT(year from re.RESERVATION_DATE);

--8 CA annuel par resort
SELECT EXTRACT(year from s.invoice_date) year, r.RESORT_NAME resort, SUM(se.PRICE*il.INVOICE_NB_GUESTS*il.INVOICE_DAYS) CA_annuel from RBONDAZ.SALES s
join RBONDAZ.INVOICE_LINE il on s.INVOICE_LINE_ID = il.INVOICE_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
join RBONDAZ.SERVICE_LINE sl on se.SERVICE_LINE_ID = sl.SERVICE_LINE_ID
join RBONDAZ.RESORT r on sl.RESORT_ID = r.RESORT_ID
group by EXTRACT(year from s.invoice_date), r.RESORT_NAME
order by EXTRACT(year from s.invoice_date);

--8 CA annuel par resort prévisionnel
SELECT EXTRACT(year from re.RESERVATION_DATE) year, r.RESORT_NAME resort, SUM(se.PRICE*il.FUTUR_GUESTS*il.RESERVATION_DAYS) CA_annuel from RBONDAZ.RESERVATION re
join RBONDAZ.RESERVATION_LINE il on re.RESERVATION_ID = il.RESERVATION_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
join RBONDAZ.SERVICE_LINE sl on se.SERVICE_LINE_ID = sl.SERVICE_LINE_ID
join RBONDAZ.RESORT r on sl.RESORT_ID = r.RESORT_ID
group by EXTRACT(year from re.RESERVATION_DATE), r.RESORT_NAME
order by EXTRACT(year from re.RESERVATION_DATE);

--9 jours vendu par année
SELECT EXTRACT(year from s.invoice_date) year, SUM(il.INVOICE_DAYS *il.INVOICE_NB_GUESTS) jours_vendu from RBONDAZ.SALES s
join RBONDAZ.INVOICE_LINE il on s.INVOICE_LINE_ID = il.INVOICE_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
join RBONDAZ.SERVICE_LINE sl on se.SERVICE_LINE_ID = sl.SERVICE_LINE_ID
join RBONDAZ.RESORT r on sl.RESORT_ID = r.RESORT_ID
group by EXTRACT(year from s.invoice_date)
order by EXTRACT(year from s.invoice_date);

--10 jours vendu par année par resort
SELECT EXTRACT(year from s.invoice_date) year, r.RESORT_NAME resort, SUM(il.INVOICE_DAYS *il.INVOICE_NB_GUESTS) jours_vendu from RBONDAZ.SALES s
join RBONDAZ.INVOICE_LINE il on s.INVOICE_LINE_ID = il.INVOICE_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
join RBONDAZ.SERVICE_LINE sl on se.SERVICE_LINE_ID = sl.SERVICE_LINE_ID
join RBONDAZ.RESORT r on sl.RESORT_ID = r.RESORT_ID
group by EXTRACT(year from s.invoice_date), r.RESORT_NAME
order by EXTRACT(year from s.invoice_date);

--11 CA par commercial
select sp.sales_person_name, SUM(se.PRICE*il.INVOICE_DAYS*il.INVOICE_NB_GUESTS) CA, EXTRACT(year from s.INVOICE_DATE) from RBONDAZ.SALES_PERSON sp
join RBONDAZ.CUSTOMER c on sp.SALES_PERSON_ID = c.SALES_PERSON_ID
join RBONDAZ.SALES s on c.CUSTOMER_ID = s.CUSTOMER_ID
join RBONDAZ.INVOICE_LINE il on s.INVOICE_LINE_ID = il.INVOICE_LINE_ID
join RBONDAZ.SERVICE se on il.SERVICE_ID = se.SERVICE_ID
GROUP BY EXTRACT(year from s.INVOICE_DATE),sp.sales_person_name
order by SUM(se.PRICE*il.INVOICE_DAYS*il.INVOICE_NB_GUESTS) desc;

--12 Prix moyen par type hebegement
Select ROUND(AVG(s.PRICE),2) prix_moyen_hébergement from RBONDAZ.SERVICE s
WHERE s.SERVICE_LINE_ID like '%1';


SELECT
  RBONDAZ.RESERVATION_LINE.FUTUR_GUESTS,
  RBONDAZ.RESORT.RESORT_NAME
FROM
  RBONDAZ.RESERVATION_LINE,
  RBONDAZ.RESORT,
  RBONDAZ.SERVICE_LINE,
  RBONDAZ.SERVICE
WHERE
  ( RBONDAZ.SERVICE_LINE.SERVICE_LINE_ID=RBONDAZ.SERVICE.SERVICE_LINE_ID  )
  AND  ( RBONDAZ.SERVICE_LINE.RESORT_ID=RBONDAZ.RESORT.RESORT_ID  )
  AND  ( RBONDAZ.SERVICE.SERVICE_ID=RBONDAZ.RESERVATION_LINE.SERVICE_ID  )


SELECT
  RBONDAZ.RESERVATION_LINE.FUTUR_GUESTS,
  R.RESORT_NAME
FROM
    RBONDAZ.RESERVATION_LINE
join RBONDAZ.SERVICE on RESERVATION_LINE.SERVICE_ID = SERVICE.SERVICE_ID
join RBONDAZ.SERVICE_LINE on SERVICE.SERVICE_LINE_ID = SERVICE_LINE.SERVICE_LINE_ID
join RBONDAZ.RESORT R on R.RESORT_ID = SERVICE_LINE.RESORT_ID
