-- 39
Select cli.NUMCATEGORIE, ROUND(AVG(cli.CA_CLIENT),2) CA from CLIENT cli
HAVING MAX(cli.CA_CLIENT) > (SELECT AVG(cli.CA_CLIENT) from CLIENT cli)
group by cli.NUMCATEGORIE;

--40
SELECT co.NUMCOMMANDE, COUNT(L.NUMCOMMANDE) NB_Commande from COMMANDE co
join LIGNECDE L on co.NUMCOMMANDE = L.NUMCOMMANDE
HAVING COUNT(L.NUMCOMMANDE) =
(SELECT MAX(COUNT(L.NUMCOMMANDE)) from LIGNECDE L group by L.NUMCOMMANDE)
group by co.NUMCOMMANDE;





